# Generated by Django 5.0.7 on 2024-07-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_maininfo_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininfo',
            name='logo',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
