# Generated by Django 5.0.7 on 2024-07-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_maininfo_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimages',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
