# Generated by Django 5.0.7 on 2024-07-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_carouselimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimages',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='logo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
