# Generated by Django 5.0.7 on 2024-07-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_dailyoffer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyoffer',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
