# Generated by Django 5.0.7 on 2024-07-28 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_items_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselimages',
            options={'verbose_name_plural': 'Carousel Images'},
        ),
        migrations.AlterModelOptions(
            name='dailyoffer',
            options={'verbose_name_plural': 'Daily Offers'},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='maininfo',
            options={'verbose_name_plural': 'Main Informations'},
        ),
    ]
