# Generated by Django 5.0.7 on 2024-07-31 06:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_order_orderlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_completed_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_created_at',
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.DeleteModel(
            name='OrderList',
        ),
    ]
