# Generated by Django 5.0.7 on 2024-07-31 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_remove_order_item_remove_order_quantity_orderlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='order_list_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.order'),
        ),
    ]
