# Generated by Django 5.0.7 on 2024-07-31 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_alter_orderlist_order_list_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.items'),
        ),
    ]
