# Generated by Django 5.0.7 on 2024-07-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_alter_orderlist_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='item',
            field=models.CharField(default='', max_length=50),
        ),
    ]
