# Generated by Django 5.0.7 on 2024-07-31 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_alter_orderlist_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlist',
            name='item',
        ),
    ]
