# Generated by Django 5.0.7 on 2024-07-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_alter_orderlist_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
