# Generated by Django 5.0.7 on 2024-07-31 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_orderlist_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlist',
            name='total',
        ),
    ]
