# Generated by Django 5.0.7 on 2024-07-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0028_remove_orderlist_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
