# Generated by Django 5.0.7 on 2024-07-31 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0030_alter_order_order_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.userprofile'),
        ),
    ]
