# Generated by Django 5.0.7 on 2024-08-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_alter_order_order_from'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyoffer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['completed', 'id']},
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
