# Generated by Django 5.0.7 on 2024-08-11 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0032_alter_dailyoffer_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselimages',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='carouselimages',
            name='title',
        ),
    ]
